name: e_commerce
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter

  # Flutter Material Design
  cupertino_icons: ^1.0.6

  # State Management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6

  # Navigation
  go_router: ^14.2.1

  # Dependency Injection
  get_it: ^7.7.0

  # UI Enhancements
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  page_transition: ^2.1.0
  rate_in_stars: ^0.0.3
  flutter_rating_stars: ^1.1.0
  like_button: ^2.0.5

  # Utility
  easy_logger: ^0.0.2
  logger: ^2.0.2+1
  envied: ^0.3.0+3
  equatable: ^2.0.5
  path_provider: ^2.0.15
  hive_flutter: ^1.1.0
  flutter_image_compress: ^2.1.0
  package_info_plus: ^4.2.0
  url_launcher: ^6.2.5
  bot_toast: ^4.1.3
  easy_localization: ^3.0.7
  connectivity_plus: ^6.0.3
  json_annotation: ^4.8.0
  dio: ^5.5.0+1
  dio_smart_retry: ^6.0.0
  pretty_dio_logger: ^1.4.0
  dartz: ^0.10.1

dev_dependencies:
  # Flutter Test
  flutter_test:
    sdk: flutter

  # Linting and Code Generation
  flutter_lints: ^3.0.0
  json_serializable: ^6.6.0
  build_runner: ^2.1.7
  very_good_analysis: ^6.0.0

flutter_gen:
  output: lib/product/utility/gen/
  line_length: 80
  integrations:
    lottie: true
    flutter_svg: true

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/translations/
    - assets/images/
    - assets/icons/
    - assets/lottie/

  # Fonts

dependency_overrides:
  carousel_slider: ^4.2.1  